const SECTOR_ORDER=['S','SV','V','JV','J','JZ','Z','SZ'];
function colorForScore(s){return s>=70?'rgba(69,201,111,.82)':s>=45?'rgba(217,182,76,.82)':s>=20?'rgba(224,95,95,.72)':'rgba(255,255,255,.08)'}
function textColorForScore(s){return s>=70?'var(--good)':s>=45?'var(--mid)':'var(--bad)'}
function fmt(v,d=1){return v===null||v===undefined||Number.isNaN(Number(v))?'?':Number(v).toFixed(d)}
function sectorMap(day){const m={}; for(const x of day.sector_scores||[]) m[x.sector]=x; return m}
function setRoseColors(card,day){const m=sectorMap(day); for(const s of SECTOR_ORDER){card.style.setProperty(`--rose-${s.toLowerCase()}`,colorForScore((m[s]||{score:0}).score))}}
function renderSectors(card,day){const c=card.querySelector('.sectors'); c.innerHTML=''; for(const x of (day.sector_scores||[]).slice(0,8)){const r=document.createElement('div'); r.className='sector-row'; r.style.color=textColorForScore(x.score); r.innerHTML=`<strong>${x.sector}</strong><div class="bar"><div class="fill" style="--w:${Math.max(0,Math.min(100,x.score))}%"></div></div><span>${Math.round(x.score)}/100</span>`; c.appendChild(r)}}
function renderDay(day){const t=document.getElementById('day-template'); const card=t.content.firstElementChild.cloneNode(true); const g=day.global||{}, sc=day.scores||{}, th=sc.thermal||{}, ce=sc.ceiling||{}, st=(day.risks&&day.risks.storm)||{}; const vli=Math.round(sc.vli??0); const dir=g.direction_deg??null; card.querySelector('.relative').textContent=day.web_label||''; card.querySelector('.date').textContent=day.date_label||day.target_date||''; card.querySelector('.vli').textContent=vli; card.querySelector('.score-badge').style.color=textColorForScore(vli); card.querySelector('.arrow').style.setProperty('--deg',`${dir??0}deg`); setRoseColors(card,day); card.querySelector('.wind-line').textContent=`Vítr z ${dir??'?'}° — ${fmt(g.mean_wind_ms)}/${fmt(g.max_gust_ms)} m/s — stabilita ${g.stability_1to5??'?'}/5`; card.querySelector('.verdict').textContent=day.verdict||'Bez slovního verdiktu.'; card.querySelector('.thermal').textContent=`${Math.round(th.score??0)}/100`; card.querySelector('.ceiling').textContent=`${ce.label||'?'} (${Math.round(ce.score??0)}/100)`; card.querySelector('.storm').textContent=st.risk||'?'; card.querySelector('.stability').textContent=`${g.stability_1to5??'?'} / 5`; renderSectors(card,day); return card}
async function main(){const res=await fetch('./data/latest.json',{cache:'no-store'}); if(!res.ok) throw new Error(`Nepodařilo se načíst data: ${res.status}`); const data=await res.json(); document.getElementById('today-title').textContent=`Dnes je: ${data.today_label}`; document.getElementById('generated').textContent=`Lokalita: ${data.location?.name||'Valašsko'} · vygenerováno ${new Date(data.generated_at).toLocaleString('cs-CZ')}`; const cards=document.getElementById('cards'); cards.innerHTML=''; for(const day of data.days||[]) cards.appendChild(renderDay(day)); const today=(data.days||[])[0]; if(today){const score=Math.round(today.scores?.vli??0); const hs=document.getElementById('hero-score'); hs.textContent=score; hs.style.background=`conic-gradient(${textColorForScore(score)} 0deg ${score*3.6}deg, rgba(255,255,255,.08) ${score*3.6}deg 360deg)`}}
main().catch(err=>{console.error(err); document.getElementById('today-title').textContent='Nepodařilo se načíst PG index'; document.getElementById('generated').textContent=err.message})
